### ISSUE TITLE
How to replicate

### ISSUE THREAD

**Issue by bennotkin** [angelinaRC/Burundi_hotspots#2]
Hi there, I'm making a set of websites for mapping city's climate conditions for the World Bank's [City Resilience Program](https://www.worldbank.org/en/topic/disasterriskmanagement/brief/city-resilience-program). I came across https://p-phung.github.io/Burundi_hotspots/ and thought it would be a great site to model our own after. Besides being very pretty, I specifically like how the scrolling helps build a narrative.

Would you mind sharing what you (and @p-phung) used to make the site? Right now we're exploring Dash, Quarto, and reveal.js.

Thank you!

**Comment by angelinaRC** [comment]
Hi @bennotkin ! We actually followed and replicated this award winning project - https://comet.dlsu.edu.ph/riesgo-vis/. They have wrote a couple of articles on how they made it, you can check it here: https://medium.com/dlsu-comet/vizrisk-flooding-in-marikina-city-a-case-study-2a59cf0dd1ba. It is based on Mapbox GL JS and React.JS

Good luck!

**Comment by bennotkin** [comment]
Thank you so much! This is incredibly helpful
